FUCKWHATDAY
A Gregorian day of week calculator written in Brainfuck

Input  eight ASCII digits YYYYMMDD then a line feed or carriage return
Output MONDAY to SUNDAY or INVALID then a line feed
Range  1900 01 01 to 2099 12 31

This annotated file is generated by the program module in tools
Every comment is free of the eight command characters so stripping
comments cannot change behaviour; the stripped copy is fuckwhatday bf
Tape map and algorithm are in ARCHITECTURE md

READ AND CHECK INPUT
  pointer at cell 0
  reads eight digits then one terminator; stops reading at the first bad byte
+
read digit0 only while still valid
if valid is not zero
add valid to scratch0 via scratch1
[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>
[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 48 49 50 51 52 53 54 55 56 57
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<------------------------------------------------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 then the first branch else the second
  +
  if scratch1 is not zero
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<-<<<<<<<<<<<<<<<<<<<<<<<<<[->+<]>------------------------------------------------
    >>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  else branch for scratch1
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]
read digit1 only while still valid
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 48 49 50 51 52 53 54 55 56 57
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<------------------------------------------------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 then the first branch else the second
  +
  if scratch1 is not zero
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<-<<<<<<<<<<<<<<<<<<<<<<<<<[->>+<<]>>------------------------------------------------
    >>>>>>>>>>>>>>>>>>>>>>>>
  ]
  else branch for scratch1
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]
read digit2 only while still valid
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 48 49 50 51 52 53 54 55 56 57
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<------------------------------------------------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 then the first branch else the second
  +
  if scratch1 is not zero
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<-<<<<<<<<<<<<<<<<<<<<<<<<<[->>>+<<<]>>>------------------------------------------------
    >>>>>>>>>>>>>>>>>>>>>>>
  ]
  else branch for scratch1
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]
read digit3 only while still valid
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 48 49 50 51 52 53 54 55 56 57
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<------------------------------------------------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 then the first branch else the second
  +
  if scratch1 is not zero
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<-<<<<<<<<<<<<<<<<<<<<<<<<<[->>>>+<<<<]>>>>------------------------------------------------
    >>>>>>>>>>>>>>>>>>>>>>
  ]
  else branch for scratch1
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]
read digit4 only while still valid
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 48 49 50 51 52 53 54 55 56 57
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<------------------------------------------------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 then the first branch else the second
  +
  if scratch1 is not zero
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<-<<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>+<<<<<]>>>>>------------------------------------------------
    >>>>>>>>>>>>>>>>>>>>>
  ]
  else branch for scratch1
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]
read digit5 only while still valid
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 48 49 50 51 52 53 54 55 56 57
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<------------------------------------------------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 then the first branch else the second
  +
  if scratch1 is not zero
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<-<<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>+<<<<<<]>>>>>>------------------------------------------------
    >>>>>>>>>>>>>>>>>>>>
  ]
  else branch for scratch1
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]
read digit6 only while still valid
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 48 49 50 51 52 53 54 55 56 57
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<------------------------------------------------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 then the first branch else the second
  +
  if scratch1 is not zero
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<-<<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>+<<<<<<<]>>>>>>>------------------------------------------------
    >>>>>>>>>>>>>>>>>>>
  ]
  else branch for scratch1
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]
read digit7 only while still valid
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 48 49 50 51 52 53 54 55 56 57
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<------------------------------------------------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 then the first branch else the second
  +
  if scratch1 is not zero
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<-<<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>+<<<<<<<<]>>>>>>>>------------------------------------------------
    >>>>>>>>>>>>>>>>>>
  ]
  else branch for scratch1
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]
read the terminator only while still valid; it must be LF or CR
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<,
  set scratch1 if char is one of 10 13
  add char to scratch2 via scratch3
  [->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>>>>>>>>>>
  [-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>]<----------
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <---
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<[-]+>>
  ]
  <[-]
  if scratch1 is zero
  +
  add scratch1 to scratch3 via scratch4
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
  ]
  <[-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>
]

ASSEMBLE NUMBERS
  pointer at cell 24
  digits are destroyed; century year month day are built
<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>++++++++++<<<<<<<<]>[->>>>>>>+<<<<<<<]>[-
>>>>>>>++++++++++<<<<<<<]>[->>>>>>+<<<<<<]>[->>>>>>++++++++++<<<<<<]>[->>>>>
+<<<<<]>[->>>>>++++++++++<<<<<]>[->>>>+<<<<]
the century must be one the supported range covers
set scratch0 if century is one of 19 20
add century to scratch1 via scratch2
>[->>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<
+>>>>>>>>>>>>>>>>]<-------------------
if scratch1 is zero
>+
add scratch1 to scratch3 via scratch4
<[->>+>+<<<]>>>[-<<<+>>>]<[
  [-]<->
]
<[
  [-]<<[-]+>>
]
<-
if scratch1 is zero
>+
add scratch1 to scratch3 via scratch4
<[->>+>+<<<]>>>[-<<<+>>>]<[
  [-]<->
]
<[
  [-]<<[-]+>>
]
<[-]
if scratch0 is zero
+
add scratch0 to scratch2 via scratch3
<[->>+>+<<<]>>>[-<<<+>>>]<[
  [-]<->
]
<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>
]
<[-]

LEAP YEAR
  pointer at cell 24
  century and year preserved; sets the mod4 and leaps cells and leap
add century to scratch0 via scratch3
<<<<<<<<<<<<<<[->>>>>>>>>>>>>>+>>>+<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>[-
<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>]
divide scratch0 by 4 into scratch1 and century_mod4
++++<<<[
  -<<<<<<<<<<+>>>>>>>>>>>>>-
  if scratch3 is zero
  >+
  add scratch3 to scratch5 via scratch6
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<++++<<<<<<<<<<<<<[-]>>>>>>>>>>>+>>>
  ]
  <<<<
]
>>>[-]<<[-]>[-]
add century to scratch0 via scratch3
<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>+>>>+<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>
[-<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>]<<<+++
divide scratch0 by 4 into century_leaps and scratch2
>>>++++<<<[
  ->>+>-
  if scratch3 is zero
  >+
  add scratch3 to scratch5 via scratch6
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<++++<[-]<<<<<<<<<<<+>>>>>>>>>>>>>
  ]
  <<<<
]
>>>[-]<<[-]>[-]
add year to scratch0 via scratch3
<<<<<<<<<<<<<<<[->>>>>>>>>>>>>+>>>+<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<
+>>>>>>>>>>>>>>>>]
divide scratch0 by 4 into scratch1 and year_mod4
++++<<<[
  -<<<<<<<<+>>>>>>>>>>>-
  if scratch3 is zero
  >+
  add scratch3 to scratch5 via scratch6
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<++++<<<<<<<<<<<[-]>>>>>>>>>+>>>
  ]
  <<<<
]
>>>[-]<<[-]>[-]
add year to scratch0 via scratch3
<<<<<<<<<<<<<<<[->>>>>>>>>>>>>+>>>+<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<
+>>>>>>>>>>>>>>>>]<<<+++
divide scratch0 by 4 into year_leaps and scratch2
>>>++++<<<[
  ->>+>-
  if scratch3 is zero
  >+
  add scratch3 to scratch5 via scratch6
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]<++++<[-]<<<<<<<<<+>>>>>>>>>>>
  ]
  <<<<
]
>>>[-]<<[-]>[-]
leap when year mod 4 is 0 and either year is not 0
or the century is a multiple of 4
if year_mod4 is zero
<<+
add year_mod4 to scratch1 via scratch2
<<<<<<<<[->>>>>>>>>+>+<<<<<<<<<<]>>>>>>>>>>[-<<<<<<<<<<+>>>>>>>>>>]<[
  [-]<->
]
<[
  [-]
  if year is not zero
  add year to scratch3 via scratch4
  <<<<<<<<<<<<<[->>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<
  +>>>>>>>>>>>>>>>>>]<[
    [-]<+>
  ]
  if century_mod4 is zero
  +
  add century_mod4 to scratch4 via scratch5
  <<<<<<<<<<<<<[->>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<
  +>>>>>>>>>>>>>>>]<[
    [-]<->
  ]
  <[
    [-]<+>
  ]
  <[
    [-]<<<<<<<<+>>>>>>>>
  ]
  <<
]

MONTH LENGTH AND OFFSET
  pointer at cell 24
  month preserved; walks a countdown through the twelve months
an out of range month never reaches zero so month length stays 0
add month to scratch0 via scratch2
<<<<<<<<<<<<[->>>>>>>>>>>>+>>+<<<<<<<<<<<<<<]>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<
+>>>>>>>>>>>>>>]<+
month 1 has 31 days
<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<+++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<+++>>>>>>
]
month 2 has 28 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<++++++++++++++++++++++++++++
  add leap to month_length via scratch4
  <[->+>>>>>>>>>+<<<<<<<<<<]>>>>>>>>>>[-<<<<<<<<<<+>>>>>>>>>>]<<
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]
  add leap to month_offset via scratch3
  <<<<<<<<[->>+>>>>>>>+<<<<<<<<<]>>>>>>>>>[-<<<<<<<<<+>>>>>>>>>]<
]
month 3 has 31 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<+++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<+++>>>>>>
]
month 4 has 30 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<++>>>>>>
]
month 5 has 31 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<+++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<+++>>>>>>
]
month 6 has 30 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<++>>>>>>
]
month 7 has 31 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<+++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<+++>>>>>>
]
month 8 has 31 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<+++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<+++>>>>>>
]
month 9 has 30 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<++>>>>>>
]
month 10 has 31 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<+++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<+++>>>>>>
]
month 11 has 30 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<++>>>>>>
]
month 12 has 31 days
<<-
if scratch0 is zero
>>+
add scratch0 to scratch3 via scratch4
<<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
  [-]<->
]
<[
  [-]<[-]<<<<<<+++++++++++++++++++++++++++++++>>>>>>>
]
if scratch1 is not zero
add scratch1 to scratch2 via scratch3
<[->+>+<<]>>[-<<+>>]<[
  [-]<<<<<<+++>>>>>>
]
<<[-]>[-]

DAY CHECK
  pointer at cell 25
  day and month length preserved; clears valid unless day is in range
if day is zero
<+
add day to scratch1 via scratch2
<<<<<<<<<<<[->>>>>>>>>>>>+>+<<<<<<<<<<<<<]>>>>>>>>>>>>>[-<<<<<<<<<<<<<+>>>>>>>>>>>>>
]<[
  [-]<->
]
<[
  [-]<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>
]
count day down against month length; reaching zero first means too big
add day to scratch0 via scratch3
<<<<<<<<<<<[->>>>>>>>>>>+>>>+<<<<<<<<<<<<<<]>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<
+>>>>>>>>>>>>>>]
add month_length to scratch1 via scratch3
<<<<<<<<[->>>>>>+>>+<<<<<<<<]>>>>>>>>[-<<<<<<<<+>>>>>>>>]<<<[
  -
  if scratch1 is zero
  >>>+
  add scratch1 to scratch4 via scratch5
  <<[->>>+>+<<<<]>>>>[-<<<<+>>>>]<[
    [-]<->
  ]
  <[
    [-]<[-]+>
  ]
  <<-<
]
>[-]>[
  [-]<<<<<<<<<<<<<<<<<<<<<<<<<<[-]>>>>>>>>>>>>>>>>>>>>>>>>>>
]

WEEKDAY
  pointer at cell 26
  runs only for valid input; inputs preserved; sets weekday
if valid is not zero
add valid to scratch0 via scratch1
<<<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]
  weekday of 1 January of year 0
  <<<+++++
  each whole century shifts the weekday by 36524 mod 7
  add century to scratch1 via scratch2
  <<<<<<<<<<<[->>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<
  +>>>>>>>>>>>>>>>>]<[-<<<<+++++>>>>]
  divide sum by 7 into scratch1 and scratch2
  >>+++++++<<<<<<[
    ->>>>>+>-
    if scratch3 is zero
    >+
    add scratch3 to scratch5 via scratch6
    <[->>+>+<<<]>>>[-<<<+>>>]<[
      [-]<->
    ]
    <[
      [-]<+++++++<[-]<+>>>
    ]
    <<<<<<<
  ]
  >>>>>>[-]<<[-]>[-<<<<<+>>>>>]
  plus one day for each 400 year leap century before this one
  add century_leaps to sum via scratch1
  <<<<<<<<<<<[->>>>>>+>>>>+<<<<<<<<<<]>>>>>>>>>>[-<<<<<<<<<<+>>>>>>>>>>]
  plus one day per year since the century began
  add year to sum via scratch1
  <<<<<<<<<<<<<<[->>>>>>>>>>+>>>>+<<<<<<<<<<<<<<]>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<
  +>>>>>>>>>>>>>>]
  plus one day per leap year since the century began
  add year_leaps to sum via scratch1
  <<<<<<<<[->>>>+>>>>+<<<<<<<<]>>>>>>>>[-<<<<<<<<+>>>>>>>>]
  less one day if that count included a non leap century year
  if year is not zero
  add year to scratch1 via scratch2
  <<<<<<<<<<<<<<[->>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<]>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<
  +>>>>>>>>>>>>>>>]<[
    [-]
    if century_mod4 is not zero
    add century_mod4 to scratch2 via scratch3
    <<<<<<<<<<<[->>>>>>>>>>>>+>+<<<<<<<<<<<<<]>>>>>>>>>>>>>[-<<<<<<<<<<<<<+>>>>>>>>>>>>>
    ]<[
      [-]<<<<<++++++>>>>>
    ]
    <
  ]
  plus the days in earlier months of this year
  add month_offset to sum via scratch1
  <<<<<[->+>>>>+<<<<<]>>>>>[-<<<<<+>>>>>]
  plus the day of the month less one
  add day to sum via scratch1
  <<<<<<<<<<<<[->>>>>>>>+>>>>+<<<<<<<<<<<<]>>>>>>>>>>>>[-<<<<<<<<<<<<+>>>>>>>>>>>>
  ]<<<<++++++
  divide sum by 7 into scratch1 and scratch2
  >>>>>>+++++++<<<<<<[
    ->>>>>+>-
    if scratch3 is zero
    >+
    add scratch3 to scratch5 via scratch6
    <[->>+>+<<<]>>>[-<<<+>>>]<[
      [-]<->
    ]
    <[
      [-]<+++++++<[-]<+>>>
    ]
    <<<<<<<
  ]
  >>>>>>[-]<<[-]>[-<<<<+>>>>]<<
]

OUTPUT
  pointer at cell 24
  prints a weekday name or INVALID then a line feed
if valid then the first branch else the second
+
if valid is not zero
add valid to scratch1 via scratch2
<<<<<<<<<<<<<<<<<<<<<<<<[->>>>>>>>>>>>>>>>>>>>>>>>>+>+<<<<<<<<<<<<<<<<<<<<<<<<<<
]>>>>>>>>>>>>>>>>>>>>>>>>>>[-<<<<<<<<<<<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>>>>>>>>>>>
]<[
  [-]<-
  add weekday to scratch2 via scratch3
  <<[->>>>+>+<<<<<]>>>>>[-<<<<<+>>>>>]<+-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]
    MONDAY
    <<<<+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    .++.-.----------.---.++++++++++++++++++++++++.-----------------------------------------------------------------------------------------
    >>>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]
    TUESDAY
    <<<<++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    .+.----------------.++++++++++++++.---------------.---.++++++++++++++++++++++++
    .-----------------------------------------------------------------------------------------
    >>>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]
    WEDNESDAY
    <<<<+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    .------------------.-.++++++++++.---------.++++++++++++++.---------------
    .---.++++++++++++++++++++++++.-----------------------------------------------------------------------------------------
    >>>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]
    THURSDAY
    <<<<++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    .------------.+++++++++++++.---.+.---------------.---.++++++++++++++++++++++++
    .-----------------------------------------------------------------------------------------
    >>>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]
    FRIDAY
    <<<<++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    .++++++++++++.---------.-----.---.++++++++++++++++++++++++.-----------------------------------------------------------------------------------------
    >>>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]
    SATURDAY
    <<<<+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    .------------------.+++++++++++++++++++.+.---.--------------.---.++++++++++++++++++++++++
    .-----------------------------------------------------------------------------------------
    >>>>
  ]
  <-
  if scratch2 is zero
  >+
  add scratch2 to scratch4 via scratch5
  <[->>+>+<<<]>>>[-<<<+>>>]<[
    [-]<->
  ]
  <[
    [-]
    SUNDAY
    <<<<+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    .++.-------.----------.---.++++++++++++++++++++++++.-----------------------------------------------------------------------------------------
    >>>>
  ]
  <[-]<
]
else branch for valid
<[
  [-]
  INVALID
  <+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  .+++++.++++++++.---------------------.+++++++++++.---.-----.--------------------------------------------------------------------
  >
]
line feed
<++++++++++.----------

END
  pointer at cell 23
  every scratch cell is zero
